### ISSUE TITLE
WYSIWYG editor

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#104]
The Visual Markdown editor is good, but the [Trix editor](https://github.com/basecamp/trix) may be more intuitive. Perhaps I should port it to Kirby as a standalone field.

**Comment by samnabi** [comment]
There are two other WYSIWYG editors on the market:

- [CKEditor](https://github.com/fishme/kirby_ckeditor) is not a finished product. It has security and setup issues.
- [WYSIWYG](https://github.com/storypioneers/kirby-wysiwyg) does not handle drag-and-drop images, nor does it save the changes in a cookie to prevent accidental data loss.

**Comment by samnabi** [comment]
Maybe I should fork the WYSIWYG editor to handle drag-and-drop, rather than implement a completely new one.

**Comment by samnabi** [comment]
Basic drag and drop is now implemented for images and pages in the sidebar.

Future enhancements could include:

- Validation and autoformatting for links (i.e. make sure http:// is there)
- Hook into the panel's autosave function
- Include live previews of dragged images and links
    - This will be difficult because of editing/publishing on different hosts.
    - Needs to support localhost, production, websites in a subfolder, etc.
    - Include alt text with images

**Comment by guidoferreyra** [comment]
Hi Sam. WYSIWYG editor throws an error on the live site. It works fine on localhost. I noticed because it prevents to Tabs field work. 
This is the error in the web inspector

`TypeError: undefined is not an object (evaluating 'e.createModule')` and leads to the rangy-core.min.js

If I disable WYSIWYG editor everything works fine.

**Comment by samnabi** [comment]
Where in the Panel is this happening?

**Comment by guidoferreyra** [comment]
The error was on the panel pages that uses WYSIWYG editor and tabs.
I've updated rangy.js and the problemas was solved. :)
