### ISSUE TITLE
Account template

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#105]
Hi Sam! I've just updated to the last version of the plugin and I noticed that the account template doesn't exist anymore. Where is the account page now?

Thanks in advance!

**Comment by samnabi** [comment]
Accounts are managed through the panel now. The user link (see screenshot) should now point to `/panel/users/username/edit`.

![screen shot 2016-11-08 at 14 56 19](https://cloud.githubusercontent.com/assets/1731536/20114759/86a11bca-a5c3-11e6-80b7-f63ddcee3793.png)

**Comment by guidoferreyra** [comment]
I've replaced my old edited snippets (head.user and head.nav) and now the buttons leads me to the user panel. So users are going to enter to the kirby panel to edit their password and info?! The "old" way was great!

This is what I see.
<img width="1280" alt="captura de pantalla 2016-11-08 a las 5 10 19 p m" src="https://cloud.githubusercontent.com/assets/1755590/20115243/4756e374-a5d6-11e6-994f-285113d8fc57.png">

If I click in "dashboard" button, appears an empty page and I I click in the "users" page it throws a php error.

thanks in advance.

**Comment by samnabi** [comment]
Now that we have permissions in Kirby 2.4.0, I thought it best not to duplicate Kirby's account management with my own templates. The panel offers better security than the old `account.php` template and controller, and I think this will reduce a lot of duplication and future maintenance.

You're right though -- there is some crucial code that was left out of the release, to simplify the UI and restrict customers' panel experience.

I'm pushing another minor release right now.

**Comment by samnabi** [comment]
(Just to give a little more context to my decision to move accounts into the panel: I also plan to move other "backend" type pages into the panel in the future. For example, a custom `Orders` page.)

**Comment by guidoferreyra** [comment]
I understand your reasons but Im not so sure about having the users on the panel with the kirby style. It looks so foreign to the site. Try to imagine you browsing a site of a brand and when you want to edit your account info the site take you to a totally totally different page without any relation with the site you were navigating. Also using the panel as customer account management cut off the possibility of customize this page. 

I've restored the account template and controller from an older version and I think it works. Again I know you probably have a lot of reasons to make this big changes but I think that is very important to always have in mind the user/customer experience.
