### ISSUE TITLE
Users can see all orders.

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#108]
In the orders page, a user with a customer role can see all the orders from the site not only his orders.

**Comment by samnabi** [comment]
Ugh. I'm sorry about this one. The `orders.php` controller and template was using `$user->hasPanelAccess()` to detect admin users, which doesn't work with the new permissions in Kirby 2.4.0. I've pushed a hotfix to the master branch.

**Comment by guidoferreyra** [comment]
Thanks!!

**Comment by guidoferreyra** [comment]
Hi sam, I was looking to the fix you sended yesterday. It solves the bug I've mentioned but when an Admin user is logged not all orders are displayed. Are you experience this issue too or just me? 
Because their are not identical, I solved this removing one `=` in this line in the cart controller 

 `} else if ($user and $user->role() === 'admin') {`

Regards.

**Comment by samnabi** [comment]
Now fixed on the master branch (again).
