### ISSUE TITLE
mysite.com/panel/login redirects to mysite.com/#login

### ISSUE THREAD

**Issue by theunique82** [samnabi/shopkit#110]
Hi,
after registering the admin user for the panel and installing it, when I try to access mysite.com/panel/login, it redirects to mysite.com/#login and shows the homepage of the website (the shop) instead of the login page. Previous version of shopkit was working perfect to me but I am updating it for the cart refresh issues of previous version. Please, I need help. Many thanks.
Vanesa

**Comment by samnabi** [comment]
This is intentional. Shopkit forces users to log in with their email and password from the frontend. So log in using the form at `mysite.com/#login`, and you'll be able to access the panel after that.
