### ISSUE TITLE
Change Checkout Process - Payment Method at the end

### ISSUE THREAD

**Issue by seehat** [samnabi/shopkit#113]
Hi, is it possible to change the checkout process to the following:

- enter all customer information, like name, mail, address, shipping method, paymentmethod 
- summary page with all collected information 
- complete the checkout and redirect to the payment method screen

**Comment by samnabi** [comment]
The current flow is intended to get customers to the payment gateway page as soon as possible, to avoid losing customers. I think people are more comfortable putting their personal information in PayPal or Stripe. And on these sites, their information might already be autofilled when they log in.

So I don't think it's a good idea to present a big form before they get to the payment gateway. That might scare customers away.

Do have some other reasons for reversing the payment flow?

**Comment by seehat** [comment]
In my opinion there are two reasons to change the flow.

## Depends on product type

As far as digital products are concerned, I agree that this flow ist the best, because in this case only the name and the email-address are required. (also concerning law)

But when selling physical products, there are more informations required, for example the address to ship the products.

And for example in austria, the law states, that these informations must be filled in, before the final confirmation and payment takes place.  So at least for austria or other european countries, there need to be the possibility for a different flow. 

My suggestion is to take customers to a checkout page/process after clicking a button in the cart and this process would be customizable like the payment gateways. So you could send the customer directly to a payment gateway or let them input data and then process to payment. Then it would also be possible to let the user select the payment method during this checkout process. 

## Payment method is not equal to the payment gateway

Another reason for this is that, there are payment gateways, which support different kinds of payment, for example https://www.mollie.com/en/pricing. Then it would be bad user experience if the payment button is titled "Pay with mollie", because the payment method is not equal to the payment gateway.

**Comment by samnabi** [comment]
The way things are currently set up, you can capture additional information in your gateway's [`process.php`](https://github.com/samnabi/shopkit/blob/master/site/plugins/shopkit/gateways/3-paylater/process.php) file, before the user is redirected.

In fact, that's exactly what the *Pay Later* gateway does, making sure we at least collect an email address, since there's no third-party gateway to collect more information.

That should provide a temporary solution while I think about this over the holidays!

**Comment by seehat** [comment]
Ok. Thank you for this hint. I will use this in the meantime.

**Comment by samnabi** [comment]
Did editing the `process.php` file give you enough flexibility in this situation?

**Comment by seehat** [comment]
I used the `process.php` file yes. But I also made more changes to the core, to bring in more orders states. thx for your help.
