### ISSUE TITLE
Confusion when adding a new page under /shop

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#118]
After testing with clients, it's clear that many people accidentally add a new category under /shop when they really wanted to add a new root-level page. Need some UX improvement here.

**Comment by invasoria** [comment]
This is a common occurrence in Kirby, not only in Shopkit. Many clients accidentally create pages where there shouldn't be a page or a category in the wrong section while thinking it was a post. A good blueprint architecture ought to work at least in theory yet it is not enough in most cases. So, a user manual or a good video tutorial is the way to go for almost any project I deliver, specially for a product like Shopkit which is practically an out-of-the-box working solution.

**Comment by samnabi** [comment]
Thanks for the insight! I think I will address this with a redesigned front-end toolbar.

This discussion is relevant too: https://forum.getkirby.com/t/change-title-for-pages-in-the-panel-per-blueprint/3286

**Comment by samnabi** [comment]
Also, maybe it's a good idea to include subpagelist... https://github.com/flokosiol/kirby-subpagelist

**Comment by invasoria** [comment]
Ah, bookmarked! Totally missed that post at the forum, looks like a promising idea.
