### ISSUE TITLE
AJAX enhancements

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#121]
Use trusty ol' hijax: https://domscripting.com/presentations/xtech2006/

Eliminate the need for a page load when swiping through items in a slideshow, changing quantities in the Cart page, etc...

(more ideas, leave them here)

**Comment by samnabi** [comment]
(merged into the New Theme issue)

**Comment by guidoferreyra** [comment]
"Add to cart" without redirecting to the cart page would be great.
