### ISSUE TITLE
Multiple orders created on multiple clicks

### ISSUE THREAD

**Issue by invasoria** [samnabi/shopkit#131]
At checkout, if a user clicks the payment/gateway buttons more than once, Shopkit, will create an order for every click, which are actually multiple form submissions. 

This is something I have solved with javascript and jQuery:

`$('#product-form').submit(function(event) {
    var $form = $(this);
    // Prevents multiple submissions
    $form.find("button").prop("disabled", true);
    $form.get(0).submit();
    return false;
});`

**Comment by samnabi** [comment]
This will be fixed in v2.0, which actually creates the pending order as soon as the customer arrives and ties it to their session ID.
