### ISSUE TITLE
Minimum and Maximum quantity.

### ISSUE THREAD

**Issue by DodoVoelkel** [samnabi/shopkit#132]
I'm using shopkit for a flea market where a potential vendor can buy Squaremeters for the market online.
We want to prevent vendors from buying less then 2 and more than 15 squaremeters.
For that reason, whould it be easy to implement a min & max cart quantity per product variant?

**Comment by samnabi** [comment]
Hm, I think introducing a per-order minimum/maximum could get quite confusing.

Maybe this is best approached with a custom fork of the `controller/cart.php`, where you can check the cart quantities before the page loads.

**Comment by samnabi** [comment]
The way to handle this currently is just having 14 different variants, one for 2 sq. m, one for 3 sq. m, ....

**Comment by samnabi** [comment]
I don't think this feature has a widespread enough use case to include in Shopkit by default. A vendor with specific needs like this will likely also require other custom changes to Shopkit.
