### ISSUE TITLE
Password reset link error

### ISSUE THREAD

**Issue by invasoria** [samnabi/shopkit#141]
This happens on a fresh 1.1.6 install.

Use the form normally with a registered email:
![image](https://cloud.githubusercontent.com/assets/1371116/25369735/b2f057ac-294b-11e7-9006-f77c267be3f4.png)

It returns an error:
![image](https://cloud.githubusercontent.com/assets/1371116/25369748/d11b7658-294b-11e7-99ed-c67c3ab2dba7.png)

But, the reset link will still go through:
![image](https://cloud.githubusercontent.com/assets/1371116/25369786/f74669c8-294b-11e7-81cc-1d583919307b.png)

After looking closely at the resetPassword() function, it seems to be missing a return to stop the error message from triggering. I added it like this (**line 377**):

![image](https://cloud.githubusercontent.com/assets/1371116/25369936/03f77242-294d-11e7-8cdd-960a9912280d.png)

**Edit:**
I just noticed you already got that solved in your dev branch! Guess it'll be included soon in an upcoming version.

**Comment by samnabi** [comment]
Yes, I'm hoping to release 1.1.7 and 2.0 simultaneously... I just wanted to wait a bit in case there are other bugs that come up in the course of testing 2.0.

Thanks for reporting this!
