### ISSUE TITLE
Update to use Kirby v2.5

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#149]

**Comment by dracnet** [comment]
any due date ?

**Comment by samnabi** [comment]
Sorry, I can't commit to a specific date at this time. I want to use some of the new translation features in 2.5.1, so that will require a bit of development before the next release.

**Comment by samnabi** [comment]
Although, if you want to `git pull` from within the `/kirby` and `/panel` folders on your existing Shopkit site, I don't anticipate any compatibility issues.

**Comment by samnabi** [comment]
Updated to 2.5.2.
