### ISSUE TITLE
Problem with Language Detection / Routing

### ISSUE THREAD

**Issue by matobeag** [samnabi/shopkit#150]
My browser is german so If I place an order with the "pay later" function, I get transferred to the wrong page on the last step:
http://shopkit.dev/shop/orders?txn_id=dfc9fe96a987042f94c763704a1958c1
![11](http://i.imgur.com/himOAnx.png)

The link should be like in the confirmation email with the detected language in the URL:
http://shopkit.dev/de/shop/orders?txn_id=dfc9fe96a987042f94c763704a1958c1
![00](http://i.imgur.com/sawGj3p.png)

Can i get rid of the I language detection completely? I tried to delete it in the config file but it still did not work.

**Comment by samnabi** [comment]
Thanks for pointing this out. I'll fix this in the next version of Shopkit.

Shopkit requires the multilanguage features of Kirby, so it's not possible to convert it to a single-language site... although perhaps you could set `DE` as the default, then remove the other language options in `config.php`. I'll have to look into that.

**Comment by matobeag** [comment]
Thanks you for the fast response. If I set `DE` as default and remove the other languages the Variants and Options disappear in the front- and backend.

**With all languages**
<img width="1200" alt="bildschirmfoto 2017-07-05 um 17 27 47" src="https://user-images.githubusercontent.com/6112475/27871985-a3de4fe6-61a7-11e7-8475-808b58d768b0.png">

**Only DE**
<img width="1200" alt="bildschirmfoto 2017-07-05 um 17 27 40" src="https://user-images.githubusercontent.com/6112475/27872043-c894ec3c-61a7-11e7-92a9-d2f4e529c70b.png">

**Comment by DodoVoelkel** [comment]
I had the same problem also.
When you are working with multiple languages, kirby is saving the content in seperate `.txt` files. like `content.en.txt` for english and `content.de.txt` for german.
If you deleted all the other languages in your config file, kirby is now looking only for the `.de.txt` file. It might be that the content was saved in the `.en.txt` file. Look for it in the content folder.

**Comment by samnabi** [comment]
That would make sense. Then the blueprint changes because it's reverting to the default blueprint.

**Comment by samnabi** [comment]
@manuelvonrotz if you follow the steps on this page (especially #4)... do you still get the same Blueprint error?

https://shopkit.samnabi.com/docs/translating-shopkit

**Comment by matobeag** [comment]
It seems to work well now! Thank you

**Comment by samnabi** [comment]
Great. There are still some bugs related to your original issue that I'm hoping to fix today.
