### ISSUE TITLE
digital product licences

### ISSUE THREAD

**Issue by enginmurat** [samnabi/shopkit#154]
regular and extended licence feature

**Comment by samnabi** [comment]
Can you elaborate on what you mean by "regular and extended"? 

I agree that license codes on a per-variant basis would be a good feature.

**Comment by enginmurat** [comment]
yes.regular licence and extended licences for template files...

**Comment by samnabi** [comment]
what would be the difference between these two license types? Is this a concept that is applicable to other types of e-commerce?

**Comment by enginmurat** [comment]
this feature for digital products

**Comment by samnabi** [comment]
I'm not sure what you mean. What is the difference between Regular and Extended licenses, in your view?

**Comment by enginmurat** [comment]
Regular licence: Use, by you or one client, in a single end product which end users are not charged for. 
Extended licence: Use, by you or one client, in a single end product which end users can be charged for.

**Comment by samnabi** [comment]
That's a little too specific to be included in Shopkit. I can see the value of a general license feature – if that gets implemented, then you can have a "Regular" variant and an "Extended" variant for your product.

**Comment by samnabi** [comment]
The next release will have this feature: a simple checkbox under `downloads` for each Variant.

![screen shot 2017-09-06 at 11 28 46](https://user-images.githubusercontent.com/1731536/30120354-99a7ef48-92f6-11e7-9b01-98a3be2e069c.png)
![screen shot 2017-09-06 at 11 28 58](https://user-images.githubusercontent.com/1731536/30120360-9c227fc2-92f6-11e7-9d07-e579bd46fb41.png)

**Comment by samnabi** [comment]
The license keys can be activated even if there isn't a download file.
