### ISSUE TITLE
member registration

### ISSUE THREAD

**Issue by enginmurat** [samnabi/shopkit#156]
member registration and member dashboard

**Comment by samnabi** [comment]
There is already a customer registration feature in Shopkit. What is missing for you?

**Comment by enginmurat** [comment]
i want to downloads and purchase history etc...in member dashboard for digital templates.

**Comment by samnabi** [comment]
Shopkit already includes downloads and purchase history. It's in the Orders page: http://yourdomain.com/shop/orders
