### ISSUE TITLE
comments and star ratings

### ISSUE THREAD

**Issue by enginmurat** [samnabi/shopkit#158]
product comments and review with stars...

**Comment by samnabi** [comment]
Still not sure whether I want to roll these features into Shopkit.

For sites that want to implement these features today, you can integrate the following plugins:

Comments: https://github.com/Addpixel/KirbyComments/
Ratings: https://github.com/jenstornell/kirby-ratings

**Comment by samnabi** [comment]
I've decided not to add these features to Shopkit. It would demand too much of my time to maintain.
