### ISSUE TITLE
Bank transfer for payment methods

### ISSUE THREAD

**Issue by enginmurat** [samnabi/shopkit#159]
can you add bank transfer for payment methods

**Comment by enginmurat** [comment]
credit card payment method

**Comment by samnabi** [comment]
Please specify a particular bank transfer system? There are many different ones around the world. Unless there are many requests for a particular gateway I will probably not implement it.

**Comment by enginmurat** [comment]
sorry; execuse me.. i want to credit card payment method...

**Comment by samnabi** [comment]
Credit cards are supported by all three gateways already offered by Shopkit – Square, Stripe, and PayPal. I don't plan to support direct credit card processing in Shopkit.
