### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#160]
Hi Sam, I'm trying to update my old version of shopkit to v2.1 and im getting the following error when the user adds an item to the cart.

Whoops says "A non-numeric value encountered" in shopkit/controllers/cart.php line 97:

```
// Get cart total
$total = cartSubtotal(getItems()) + cartTax() + page(s::get('txn'))->shipping()->value;
```

Could you please help with this

Best.

**Comment by guidoferreyra** [comment]
Same happens with the default site you provide.

**Comment by samnabi** [comment]
This looks like a similar error to https://github.com/samnabi/shopkit/commit/37b7b5f433cd4e483e7b7e97952c3be7ece528f9

**Comment by samnabi** [comment]
As a hotfix, I would try casting the shipping value as `(float)`.
`$total = cartSubtotal(getItems()) + cartTax() + (float) page(s::get('txn'))->shipping()->value;`

**Comment by guidoferreyra** [comment]
Fixed, thanks!
