### ISSUE TITLE
100% discounts

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#165]
Hi Sam, I noticed if I want to make a discount for the total of the product value the discount is not applied. Could you help me with this?

Best.

**Comment by samnabi** [comment]
I can't replicate this issue. Are you setting a 100% discount code in the Site Options?

What discount amount shows up?

Can you show a screenshot of the cart page?

**Comment by guidoferreyra** [comment]
I’m not using a discount code just a discount at product>variant option.
If I set Sale Price to 0 it doesn't perform any discount. If set, for instance, to 1 all works fine.

Panel setting
![captura de pantalla 2017-09-05 a las 12 43 41 p m](https://user-images.githubusercontent.com/1755590/30070309-6f1a1944-9239-11e7-861a-b322eecb8cc4.png)

Result
![captura de pantalla 2017-09-05 a las 12 44 09 p m](https://user-images.githubusercontent.com/1755590/30070328-7d1543a2-9239-11e7-9a1c-2255b9249da7.png)

If I set to other value different to 0
![captura de pantalla 2017-09-05 a las 12 43 19 p m](https://user-images.githubusercontent.com/1755590/30070365-8e189302-9239-11e7-84bd-73b8c455518e.png)

**Comment by samnabi** [comment]
Aha, okay. This looks like a `false == 0` problem. I'll issue a bug fix soon.

**Comment by samnabi** [comment]
Fixed on the master branch.

**Comment by guidoferreyra** [comment]
Hi again. When the total of the cart is zero? Is possible to bypass the gateway process?

**Comment by samnabi** [comment]
Good catch! I've fixed this on the master branch. If the cart total is 0, all other gateways will disappear and the button will day "Confirm order" (this is what was already happening for orders where a giftcard paid for the entire order).

**Comment by guidoferreyra** [comment]
Sorry for reopening this I think there a little bug. If paylater setting is disabled it doesn't displays the confirm button. You are having the same issue?

**Comment by samnabi** [comment]
Hmm... the more I look at this problem, I realise that maybe you shouldn't be able to disable the `Pay Later` gateway.

If `Pay Later` is enabled, but restricted to admin only – is that a problem?

**Comment by guidoferreyra** [comment]
It works if is enabled and restricted to admin only. In my case is not a problem maybe it is for other Shopkit users.
