### ISSUE TITLE
Accommodate multiple payment gateways

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#17]
Leaning towards [Omnipay](http://omnipay.thephpleague.com/gateways/official/).

I have a good handle on North American payment gateways that people use, but I'd love some perspective from other parts of the world. Does Omnipay offer what you need?

**Comment by seb-celinedesign** [comment]
What about Bank transfer ?

**Comment by samnabi** [comment]
What bank were you thinking of? Looks like this is possible for some Moneris account holders, but otherwise might have to go through a third-party payment processor.

http://stackoverflow.com/a/142713

**Comment by seb-celinedesign** [comment]
I was talking about offline payment in general, like check and transfer.

**Comment by samnabi** [comment]
Ah, I see. There is a "pay later" option that you can enable for certain account types.

**Comment by samnabi** [comment]
This is in the shop options: domain.com/panel/#/pages/show/shop/p:1
![screen shot 2015-09-06 at 14 06 18](https://cloud.githubusercontent.com/assets/1731536/9705841/79ed0116-54a0-11e5-8893-007a456f65bb.png)

**Comment by hotmeteor** [comment]
Would you consider a Stripe integration? That would seal the deal for us.

**Comment by samnabi** [comment]
Stripe can be handled by OmniPay, so that's looking like a good option. Unfortunately v1.0 won't include this out of the box, but that's because v1.0 is just around the corner :)

**Comment by samnabi** [comment]
v1.0 will have an extendable gateway structure, so it should be fairly easy to add logic for any gateway:

![screen shot 2015-09-08 at 22 44 17](https://cloud.githubusercontent.com/assets/1731536/9752159/2f52d5ea-567b-11e5-94b1-4f4a4a64f87d.png)
