### ISSUE TITLE
Allow only logged users.

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#171]
Sorry for this silly question, but I can’t find where to set that only logged users can buy products.
Best.

**Comment by samnabi** [comment]
This isn't possible currently. If you restrict purchases to only those who are logged-in, you will also have to introduce a approval process when they register.

What kind of approval process do you need?

**Comment by guidoferreyra** [comment]
Approval process? I don't understand.

I think I achieved what I want adding the following in the cart template 
`<?php if ($site->user()): ?>`
So if the user is logged it displays the gateways, but if not it displays a login for. So far all works fine Now I I'm in the process of adding a register form.

I’m in the right path?

**Comment by samnabi** [comment]
There is already a registration form in Shopkit. (`domain.com/account/register`)

Anyone can register. So if you restrict pages to logged-in users, you're really not restricting anything – anyone can make an account and log in.

**Comment by guidoferreyra** [comment]
Yes im reusing the register form. Yes, I only want to restrict anonymous purchases, I want to lead users to create an account.

**Comment by samnabi** [comment]
Name and email is always required by the `confirm.php` page – this is the step after payment gateway, and is usually pre-populated by the customer's payment information.

The reason I developed it this way is to make the checkout as seamless as possible.

If you need more information beyond name and email, you can also require a mailing address under `Site Options > Shipping & tax` in the panel.
