### ISSUE TITLE
Registration Email validation

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#172]
For some strange reason, when the user registers in the English (default language) version of my site, the email with the activation link is not sended. If the user registers in my other language Spanish everything works fine. 
I activated the mail log to see if some error is happening, but there is no error in the messages registered.

Any idea? Thanks in advance.

**Comment by samnabi** [comment]
I can't replicate this issue – does the English email not send at all, or is there no activation link?

**Comment by guidoferreyra** [comment]
The email is not sent at all. Very strange.

**Comment by guidoferreyra** [comment]
Any idea where to look? The error is very consistent, the emails fails everytime in the english version but never on the spanish version of the site.

**Comment by samnabi** [comment]
When you activated the mail log, are both English and Spanish messages showing up there?

**Comment by guidoferreyra** [comment]
Both languages are recorder and none error is recorded, everything works fine. Could be related to my hosting or php version?

**Comment by guidoferreyra** [comment]
I solved this using Mailgun as email service.

**Comment by samnabi** [comment]
Okay. Sorry I couldn't figure this one out, it seems like an odd issue on your server.

I'm a big fan of dedicated email APIs, Postmark has solved so many headaches for me!
