### ISSUE TITLE
Cannot test checkout

### ISSUE THREAD

**Issue by TimOetting** [samnabi/shopkit#174]
Hey samnabi,

I just cloned shopkit 2.2 and copied the test content to play around a bit. However, there seems to be a problem with the checkout: After choosing payment method I get these php errors:

```

Warning: number_format() expects parameter 1 to be float, array given in /Users/tim/Dropbox/Server/htdocs/sandbox/shopkit/site/plugins/shopkit/controllers/process.php on line 31

Warning: Cannot modify header information - headers already sent by (output started at /Users/tim/Dropbox/Server/htdocs/sandbox/shopkit/site/plugins/shopkit/controllers/process.php:31) in /Users/tim/Dropbox/Server/htdocs/sandbox/shopkit/kirby/vendor/getkirby/toolkit/lib/header.php on line 251

Warning: Cannot modify header information - headers already sent by (output started at /Users/tim/Dropbox/Server/htdocs/sandbox/shopkit/site/plugins/shopkit/controllers/process.php:31) in /Users/tim/Dropbox/Server/htdocs/sandbox/shopkit/kirby/vendor/getkirby/toolkit/lib/header.php on line 252
```

I had a quick look in the source code and well, just as the error says, you use `cartTax()` as the as the first parameter of `number_format()`. And `cartTax()`returns ans array :)

**Comment by guidoferreyra** [comment]
Im Getting the same number_format() error

**Comment by guidoferreyra** [comment]
If I modify in process.php
`'tax' => number_format(cartTax(),2,'.',''),`
for 
`'tax' => number_format(cartTax()['total'],2,'.',''),`

I think it works

**Comment by samnabi** [comment]
Yes, I overlooked that line when I changed the `cartTax()` function to allow displaying more granular tax information! 

It's fixed on the master branch now.
