### ISSUE TITLE
After Paypal payment update status.

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#176]
Hi Sam, me again :)
After the payment is made in Paypal and go back to the site, the user confirms the order but the status is not changed, still on "Pending". Are you having this same issue? In case you don't can you point me where file to look and check if I have differences to the your files.

Thanks in advance.

**Comment by samnabi** [comment]
Is your site using HTTPS (SSL certificate and green lock in the URL bar)? I know that PayPal will not send customer data, including the transaction status, to the Shopkit site unless it is an HTTPS connection.

**Comment by guidoferreyra** [comment]
I don't have SSL. I think I should get one.
Thanks for the info.

**Comment by thomasverleye** [comment]
Hi, Is it possible to test this on a local test environment with a self-signed certificate? I've been testing this but I can't seem to figure how to get this working localy.
