### ISSUE TITLE
Show Price with Tax

### ISSUE THREAD

**Issue by Mojo90** [samnabi/shopkit#179]
In Germany we have to show the complete price for the customer. 
So e.g. I want to have 10€ for a product and we have 19% VAT on most things, so that is 11,90€ in total. Thus you have to show in the product to the customer 11,90€ and not only 10€.

As I saw it with first testing there are always shown the net prices in the products and then in the sopping cart the taxes are added or did I miss something? This way is not practible for a german store based on this.
Is there a simple way to print out the total price in the product overview and product detail view?

**Comment by samnabi** [comment]
This is a feature I'm actively working on, and will be released officially in the next version.

It's already on the Master branch right now, if you want to try it out. Simply check the box under the **shipping & tax** tab in Site Options.

![screen shot 2017-10-23 at 07 46 52](https://user-images.githubusercontent.com/1731536/31887440-670efe2e-b7c6-11e7-9676-88bd08658473.png)

**Comment by Mojo90** [comment]
Ah great thx for the info! Will check it out by end of the week!
