### ISSUE TITLE
Doesn't work in subdirectory

### ISSUE THREAD

**Issue by differenceclouds** [samnabi/shopkit#18]
For my purposes, I would rather not install this in the root directory, but it doesn't seem to work in a subdirectory. Any tips here? I'm using MAMP btw.

**Comment by samnabi** [comment]
Can you give some more details about the errors you're receiving and the steps to replicate them?

**Comment by ghost** [comment]
Oh noooo...
http://localhost/shop/

When will 1.1 be released, can´t use/buy your shop until subdirectory works, I changed
it in config but it seems to be broken on a lot of places...

**Comment by samnabi** [comment]
I may have been too restrictive with the `config.php` settings, which are causing this issue.

```
    c::set('url', 'http://'.$_SERVER['HTTP_HOST']);
```

I will try to have version 1.0.1 released by Christmas, with a lot of bugfixes. 

In the meantime, try commenting out line 58 of `/site/config/config.php` and see if that works.

**Comment by samnabi** [comment]
you're right; this was a more widespread issue than just the config file. I've cleaned up the URL output in all the template files and this will be resolved in 1.0.1.
