### ISSUE TITLE
Status order mail and product link

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#180]
Hi Sam. If a pending order is marked by the admin as abandoned the buyer receives an email with the Order Details but this mails contains the link to the digital product. So the buyer will be getting the files that he didn't paid.

**Comment by samnabi** [comment]
Thanks, the same logic now applies to download codes as the display of license keys – only paid and shipped transactions will display them (both in the email and in the orders page)

**Comment by guidoferreyra** [comment]
Great! This fix will be available in the next release or should I take the code from the repository?

**Comment by samnabi** [comment]
v2.3 is now released, and includes this fix.
