### ISSUE TITLE
Windows colon issue in URL Parameters

### ISSUE THREAD

**Issue by hroma** [samnabi/shopkit#183]
I was testing your Great Kit! I have only a small issue as I'm testing it on XAMPP/Windows. All urls with URL parameters returns 404 error.

For Windows testing users, I would recommend  to use a semicolon (;) instead of a colon (:) for URL params.

For example (controller/process.php at line 60) you currently have: 
`go($page->url().'/gateway:'.get('gateway').'/id:'.page(s::get('txn'))->txn_id());`

would be better to use "**url::paramSeparator()**"   instead of "**:**" :
`go($page->url().'/gateway'. url::paramSeparator() .get('gateway').'/id'. url::paramSeparator().page(s::get('txn'))->txn_id());
`
The above would fix the 404 errors for Windows Based Localhost/Servers.
Best,

**Comment by invasoria** [comment]
Ah, yes. This is something I've been meaning to report for a long time. Local testing on Windows based systems will throw this error.

**Comment by samnabi** [comment]
Thanks! I will get a fix for this soon; just missed the v2.3 release window but it will be available in the master branch until the next release.

**Comment by samnabi** [comment]
This fix is now is the master branch.
