### ISSUE TITLE
Inclusive Taxes

### ISSUE THREAD

**Issue by Mojo90** [samnabi/shopkit#185]
I upgraded to V2.3 where you included the inclusive tax calculation. I upgraded with copying the kirby, panel and plugin folder, is that enough?
In the settings it states `tax = (tax rate * price) / (1 + tax rate)`, so far so good that should be corret.
But when I test it with a product which is 16,90€ with 19% Tax than there it shows up with 1€ in Tax which is wrong, it should be 2,70€.
Whats wrong here? And what about the Shipping Fee there it is also included?
So in my opinion in the picture below the total price should be 16,90€ (price) + 6,90€ (tax) = 23,80€.

<img width="655" alt="screen shot 2017-11-19 at 11 01 45" src="https://user-images.githubusercontent.com/2122156/32989596-aae3c50e-cd19-11e7-9db5-fa84b0e85070.png">

UPDATE:
On the Panel Overview Site it states for me: `You're using v2.2  Upgrade to v2.3`. So then the above method is not enough what I did. What have I missed? What is the best way to update so that my own templates/snippets and so on will not get overwritten?

**Comment by samnabi** [comment]
This page lists all the changes to Shopkit from v2.2 to v2.3: https://github.com/samnabi/shopkit/compare/v2.2...v2.3

Use these terminal commands to update Shopkit and its dependencies:

```
git checkout master
git pull origin master
git submodule update --init --recursive
```

Then you will need to manually update your custom templates, controllers and snippets since they will still be based on the v2.2 code.

**Comment by Mojo90** [comment]
Yeah I saw this somewhere in the docs how to update and it didn't work for me so I tried manually as mentioned above in the 2nd sentence.
So I have following `.gitmodules`-File in my root folder:

```
[submodule "kirby"]
	path = kirby
	url = https://github.com/getkirby/kirby
[submodule "panel"]
	path = panel
	url = https://github.com/getkirby/panel.git
[submodule "site/plugins/field-bidi"]
	path = site/plugins/field-bidi
	url = https://github.com/samnabi/field-bidi.git
[submodule "site/plugins/field-multiselect"]
	path = site/plugins/field-multiselect
	url = https://github.com/distantnative/field-multiselect.git
[submodule "site/plugins/field-selector"]
	path = site/plugins/field-selector
	url = https://github.com/storypioneers/kirby-selector.git
[submodule "site/plugins/shopkit/fields/color"]
	path = site/plugins/field-color
	url = https://github.com/ian-cox/Kirby-Color-Picker.git
[submodule "site/plugins/shopkit/fields/tabs"]
	path = site/plugins/shopkit/fields/tabs
	url = https://github.com/afbora/Kirby-Tabs-Field
[submodule "site/plugins/shopkit/fields/field-wysiwyg"]
	path = site/plugins/field-wysiwyg
	url = https://github.com/samnabi/kirby-wysiwyg
[submodule "site/plugins/stats"]
	path = site/plugins/stats
	url = https://github.com/samnabi/kirby-stats.git
[submodule "site/plugins/shopkit/gateways/stripecheckout/stripe-php"]
	path = site/plugins/shopkit/gateways/stripecheckout/stripe-php
	url = https://github.com/stripe/stripe-php
[submodule "site/plugins/shopkit/gateways/square/connect-php-sdk"]
	path = site/plugins/shopkit/gateways/square/connect-php-sdk
	url = https://github.com/square/connect-php-sdk
[submodule "site/plugins/kirby-snippetfield"]
	path = site/plugins/kirby-snippetfield
	url = https://github.com/jenstornell/kirby-snippetfield
[submodule "site/plugins/dompdf"]
	path = site/plugins/dompdf
	url = https://github.com/samnabi/dompdf/
[submodule "site/plugins/responsive-images"]
	path = site/plugins/responsive-images
	url = https://github.com/jancbeck/kirby-responsive-images
```

But when I do in my root folder of this project:
```
mo$ git submodule update --init --recursive
mo$
``` 
nothing happens and in the panel overview still it says `You're using v2.2 Upgrade to v2.3`.

**Comment by samnabi** [comment]
Can you tell me what the folder structure is within `site/plugins/dompdf`? I upgraded this plugin for 2.3 and want to make sure you have the right files.

**Comment by Mojo90** [comment]
<img width="225" alt="screen shot 2017-11-21 at 22 40 45" src="https://user-images.githubusercontent.com/2122156/33098252-15ed6fa4-cf0d-11e7-85da-590b6a9f2878.png">

**Comment by samnabi** [comment]
This is the old file structure. It looks like there's actually an incorrect reference to the dompdf submodule in `.gitmodules`. It should be at `501ff6d` instead of `aba268b`...

Separately, what version of Kirby and Panel do you have? You can see that in the sidebar of Site Options in the Panel.

I would also be good to get a list of all the files you've customized.

**Comment by Mojo90** [comment]
For dompdf I copied the commit `501ff6d` in the directory and then it looks like this:
<img width="159" alt="screen shot 2017-11-25 at 13 17 48" src="https://user-images.githubusercontent.com/2122156/33230411-2f06e640-d1e3-11e7-8a8c-e055671c4d58.png">
But the result is the same: Shopkit still says `You're using v2.2  Upgrade to v2.3`

Regarding kirby:
```
Toolkit Version: 2.5.7
Kirby Version: 2.5.7
Panel Version: 2.5.7
```

At the moment my customized files:
<img width="174" alt="screen shot 2017-11-25 at 13 13 13" src="https://user-images.githubusercontent.com/2122156/33230359-739b7a42-d1e2-11e7-9061-cc92179c01e3.png">

**Comment by samnabi** [comment]
Can you send me a .zip file of your site to sam@samnabi.com? Might be easier to debug this outside of github.

**Comment by Mojo90** [comment]
Thx, you should have a mail!
