### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by Mojo90** [samnabi/shopkit#186]
This occurs everytime when I change the amount of products in the cart - so e.g. switching from amount 1 to 2 or vise verca. And the weird thing is, this is the same product as in #185 and as you can see it cuts the cents because the product is brutto 16,90€...

<img width="1036" alt="screen shot 2017-11-19 at 11 02 06" src="https://user-images.githubusercontent.com/2122156/32989707-e56353c8-cd1b-11e7-9662-561d9737fde8.png">

**Comment by samnabi** [comment]
This looks like the same issue as #185
