### ISSUE TITLE
Cast transaction values as float when claculating total

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#193]
Line 13 of gateways/stripecheckout/process.php

`$amount = $txn->subtotal()->value + $txn->shipping()->value - $txn->discount()->value - $txn->giftcertificate()->value;`

Line 101 of snippets/order.details.php

`$total = (float)$txn->subtotal()->value + (float)$txn->shipping()->value - (float)$txn->discount()->value - (float)$txn->giftcertificate()->value;`

Maybe more?

**Comment by HermesHarmony** [comment]
Hi Sam,
Is there a solution for this problem? Or a workaround?
