### ISSUE TITLE
Per item shipping counts Free Shipping Items

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#195]
Hi Sam. I’ve noticed If I set a shipping with a rate per item, in the cart page, it also counts free shipping items.
In the attached image you will see how the shipping is calculated to $24 when I’ve set the shipping to $12.

Best.
![captura de pantalla 2017-12-28 a las 4 01 04 p m](https://user-images.githubusercontent.com/1755590/34420511-c35c528e-ebe8-11e7-942b-255b35484159.png)

**Comment by samnabi** [comment]
Are you using the latest code from the master branch? If so, it includes a new per-product shipping rates feature that replaces the old "Free shipping" checkbox.

What does the `Shipping & Tax` tab for Producto 2 look like in the panel?

Did you override any of Shopkit's default blueprints?

**Comment by guidoferreyra** [comment]
Hi! I’m using the last release. I will download the master branch. Thanks!
