### ISSUE TITLE
Product custom shipping rate

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#196]
I think it be very useful custom shipping rates per product like you implemented for the taxes.
In my case I really need this feature because not all products have the same origin.
How difficult would it be to implement this? Any hint?

**Comment by samnabi** [comment]
I've actually just added this feature to the Master branch: https://github.com/samnabi/shopkit/commit/99560886cb54fcea774a05d92985bf4547fff7a2

This replaces the old "Free Shipping" checkbox, so your product blueprints might need to be updated if you previously marked them with "Free Shipping".

This will be documented in the next release :)
