### ISSUE TITLE
Error on creating new account

### ISSUE THREAD

**Issue by brainandbrain** [samnabi/shopkit#198]
Just installed Shopkit and tried to create a new account, but I'm getting this error:

`include(../site/plugins/shopkit/registry/../fields/tabs/tabs.php): failed to open stream: No such file or directory`

There are no folders inside `../plugins/shopkit/registry/ `in my installation, only files. There is a `../plugins/shopkit/fields/tabs/` folder, but it's empty. I checked this against a fresh download of Shopkit, but it's the same. Am I missing something?

**Comment by brainandbrain** [comment]
Update: I was able to find the missing files in v2.2 and copy them over to solve this. @samnabi Looks like the contents of `../site/plugins/shopkit/fields/tabs/` are missing from v2.3.

**Comment by samnabi** [comment]
This folder is a submodule, so to populate you will need to make sure to update submodules and clone the repo using `--recursive`.
