### ISSUE TITLE
Empty cart method?

### ISSUE THREAD

**Issue by invasoria** [samnabi/shopkit#199]
What would be another way of achieving this?

I understand that destroying and restarting a session is the current method of doing this but it also forces the user to logout since the user-session data is stored there.

What I'm trying to do is to keep a user logged in after completing a purchase, emptying only the cart and not destroying the whole session. I tried by clearing the 'txn' property in the session but this doesn't work since it's persisting through (I think) this part:

```
if (page('shop/orders/'.s::id())) {
  s::set('txn', 'shop/orders/'.s::id());
  page(s::get('txn'))->update(['session-end' => time()], $site->defaultLanguage()->code());
}
```

**Comment by samnabi** [comment]
I would suggest:

1. Store the username in some variable
2. Destroy the session and log out
3. Use `$user->loginPasswordless()` to log the user in again

**Comment by invasoria** [comment]
Thanks Sam, this sounds like a good way to do this!
