### ISSUE TITLE
When a non-panel user makes a purchase, fatal error

### ISSUE THREAD

**Issue by aftereffectsmagic** [samnabi/shopkit#2]
Integrating Shopkit into an already existing Kirby install with a built-out site. I've been testing Shopkit via a clean Kirby installation and as an integrated part of my existing site, and tested this issue via both methods.

When I attempt to make a Sandbox purchase and I'm not logged into the panel, I see this when I'm sent back to /shop/orders via the Paypal link: 

<b>Orders

All the transactions are listed here.

Fatal error: Call to a member function hasPanelAccess() on boolean in /data/16/1/21/162/1510651/user/1625459/htdocs/dev2/site/templates/orders.php on line 34</b> 

This happens via either a clean install or an integrated approach:

CLEAN KIRBY INSTALL as /shopkit directory on my server
1. I am not logged into the site as an user- this error keeps appearing. 

INTEGRATION INTO EXISTING KIRBY SITE
1. I am not logged into the site as a panel administrator- this error keeps appearing. 

My goal is not to have a required registration as part of the site, as I can't seem to get that feature to work as part of an existing Kirby installation (yet!). I'd like folks who make purchases to be able to see their most recent order, however, and not have this error throw. 

Let me know if I need to provide more info in order to solve this issue. Thanks!

**Comment by samnabi** [comment]
Please pull the most recent code and give it a try. I've added the ability to view one order on the "View Orders" page, by passing the PayPaltransaction ID through a GET variable. Like this:

`http://testshop.com/shop/orders?txn_id=74X1260270218230X`

This is now built into the return URL from PayPal, so if someone is not logged in they will just see that one transaction.

I'll keep this issue open until you can confirm there are no other problems.

**Comment by aftereffectsmagic** [comment]
Thanks for uploading the bug fix. I changed three files based on your recent changes: templates/cart.php, templates/orders.php and config.php. The fatal error message is completely gone regardless of my log status, which is great!

Unfortunately, though, I am still not displaying the single order that I want to display for non-logged in users. It seems like the PayPal transaction ID (txn_id) gets passed, but the invoice only appears as part of a comprehensive list of orders if I am logged in as a Panel user and not at all when I am not logged in at any level. 

When a PayPal payment is completed, the user gets returned to: 

`http://testshop.com/shop/orders?txn_id=74X1260270218230X`

so looks like the PayPal transaction ID passes, but no invoice appears. The only messages that appear are: 

<b>All the transactions are listed here.

To see the orders associated with your email address, please register or log in.</b>

Thoughts?

**Comment by samnabi** [comment]
I just tried this on a fresh install of Shopkit, and it seems to be working.

Is your testing environment accessible from a public URL? PayPal creates the transaction record in the background before the user is redirected to the `/shop/orders` page. This means that PayPal's servers need to be able to access that URL. It won't work in a local testing environment.

**Comment by aftereffectsmagic** [comment]
Thanks for the reply! It's accessible from a public URL,  yes,  and the
transaction goes through on via a PayPal Sandbox account,  but an invoice
only appears if I'm logged in as a panel user.

**Comment by samnabi** [comment]
Interesting, just to confirm: does this happen if you install a new Shopkit from scratch? Or only when you have integrated the files into your existing Kirby setup?

**Comment by samnabi** [comment]
As I can't replicate this, I'm going to close the issue.
