### ISSUE TITLE
Some Stripe transactions failing

### ISSUE THREAD

**Issue by peteeveleigh** [samnabi/shopkit#203]
I'm using Shopkit for the first time and have been very impressed but I've run into a problem that I'm having trouble resolving.

Using the Stripe gateway in test mode I'm finding that some transactions through stripe aren't returning to the proper URL.

The payment will go through OK but the customer ends up back at the cart and the order is marked as "pending". I'm seeing the following error notification in an email from the store. 

"A payment was received, but it doesn't match the order that was placed."

Some orders go through without any problem at all and I'm having trouble nailing down what is going wrong.

UPDATE: I've noticed that orders which get set to pending don't have a value against Payer-id
UPDATE 2: It seems to be something to do with the "amount" check. I did run into the problem with values not being cast as floats so it may be something to do with that.

**Comment by peteeveleigh** [comment]
Further to this, I've tried using the Paypal checkout. This appears to work in as much as it returns to the order confirmation/receipt page but the stock level aren't being reduced.

**Comment by peteeveleigh** [comment]
I'm tentatively offering a solution for this.
It's related to the prices being charged and the way PHP adds up floating point numbers. What you "see" isn't necessarily what PHP is dealing with behind the scenes. For instance, 16.90 might just be a representation of the number PHP has in memory and the real value may be slightly different.

See here. https://andy-carter.com/blog/don-t-trust-php-floating-point-numbers-when-equating

The failure was happening in stripecheckout/callback.php around line 47

`if ($charge->amount == $amount * 100) {`

Where $amount was calculated from adding up the price, tax, shipping and subtracting any discounts.

I change the line to be

`if ((string) $charge->amount == (string) ($amount * 100)) {`

Casting both values to a string (rather than a float, which would retain the inaccuracies) means we are comparing like for like and the 2 "numbers" are the same.

So far this seems to have fixed the problem.

**Comment by samnabi** [comment]
Thank you for the detailed report and proposed solution. I agree that your fix makes sense – the paypal validation uses rounding to explicit decimal places when validating the amount, so that makes total sense.

**Comment by peteeveleigh** [comment]
I'm afraid this issue isn't completely fixed. While the transactions now appear to go through, the user is returned to a page that has the sidebar and says "Orders" at the top but no other content.

**Comment by peteeveleigh** [comment]
My client has ended up going with a Wordpress/Woocommerce option instead so she could get up and running. I think she may be contacting you for a refund I'm afraid.

**Comment by samnabi** [comment]
No worries – thanks for the additional information about this bug. I'll keep this issue open and do some more thorough testing when I have the time.

**Comment by samnabi** [comment]
@fantasticmachine does the "Orders" page you see look like this, but without anything below the **Orders** title?

I'm afraid I can't duplicate the error. If you're able to reproduce it, can you specify what URL you see in the address bar?

![screen shot 2018-06-06 at 14 52 41](https://user-images.githubusercontent.com/1731536/41059183-d4a9edec-6999-11e8-8f69-142c52af48ab.png)

**Comment by samnabi** [comment]
Closed due to inactivity. Please reopen if someone comes across this issue again.
