### ISSUE TITLE
Multi-Language Shop: Some Questions

### ISSUE THREAD

**Issue by V0IDNIL** [samnabi/shopkit#204]
Hi Sam,
My apologies if these questions have been answered, but I couldn't really find conclusive answers elsewhere.

I am looking into using shopkit for a small multi-lingual online shop. Japanese/English in the beginning and potentially German/French/Chinese later on. 

1) We are selling handcraft items, so running low on/out of stock will be the norm rather than the exception. Now, I would like to set up a product variant with a limited stock quantity in my main language and only translate the variant name into the other language(s). But if I do so, then I also have to set up a separate stock quantity for them, each of which will be treated separately. I was hoping that deleting the _**stock**_ structure field entry from my secondary language (product.en.txt) would revert to the value from my primary language (product.ja.txt) but that just sets the quantity of the secondary language to unlimited.
I see that you opened #189 which I think addresses this issue. 
Is having a global stock quantity actually something that is technically possible, and if so, how far up your priority list is this issue?

2) In #12, you say that you don't plan to support multi currency stores. I was wondering though why it's possible to select a different currency for each language in the site options (instead of setting those fields to translate: false in the blueprint). Right now shopkit allows me to display a different currency in the store for each language and I could set a different product price per language/currency. Since it's also possible to assign a different Stripe/Paypal account for each language, do I assume correctly that I could just route each language to a different Stripe/Paypal account and thus actually could couple each language with a different currency?

Thank you! Really love what I see so far with shopkit. Especially for smaller online shops it seems to be much better suited than all those full-scale/bloated competitors.

Klaas

**Comment by samnabi** [comment]
Shopkit has never been intended to have translated page fields. The Panel was intended to be used with the default language only.

A global stock quantity is the way it is intended to work.

So the behaviour you see is unintended – I have now set `translate: false` on many of the site's fields. Unfortunately, I get a `item not found` error when trying to use `translate: false` on only certain parts of a structure field. The whole structure field must be enabled or disabled for translation. 

This means translated variant names are not possible.
