### ISSUE TITLE
Registration and Password Reset does not work

### ISSUE THREAD

**Issue by Mojo90** [samnabi/shopkit#205]
I get the link to the mail address (<host>/token/<token-id>) but when clickin on the link just the startpage is opened and I think that is not the desired behaviour. 
Example page to test: http://federleichtdesignatelier.de

**Comment by samnabi** [comment]
This was a difficult one to track down. When the `nobody` panel role was [introduced in Kirby 2.5.6](https://getkirby.com/changelog/kirby-2-5-6), it caused some issues with Shopkit's custom `customer` role. In short, the permission fallback did not work as expected.

This has now been fixed. Please note that there is a new folder, `site/ roles/`, which makes sure that the `customer` role is defined before the panel permissions checks need to happen.
