### ISSUE TITLE
Image Quality

### ISSUE THREAD

**Issue by Mojo90** [samnabi/shopkit#206]
I recognized that the image thumbs are in a very bad quality when uploading images for a product. 
E.g.:
- the Product overview (http://federleichtdesignatelier.de/thumbs/shop/prints-als-download/oh-happy-day/bilderrahmen-oh-happy-day-400x331.jpg)
- and Product Detail View (http://federleichtdesignatelier.de/thumbs/shop/prints-als-download/oh-happy-day/bilderrahmen-oh-happy-day-580x480-q80.jpg) 
- vs. the original one (http://federleichtdesignatelier.de/content/2-shop/4-prints-als-download/1-oh-happy-day/bilderrahmen-oh-happy-day.jpg).

Is there a setting to use the original ones? When not that the quality is not getting that bad? Because imho that looks really awful with those bad images: http://federleichtdesignatelier.de/shop/prints-als-download

**Comment by samnabi** [comment]
Yes, there will always be a trade-off between file size and quality. 

Here are the lines where image resizing happens. You will have to modify them.

Product detail slider: https://github.com/samnabi/shopkit/blob/fcb1a124c753e6934fa5ce4dd317375cb9b8138c/site/plugins/shopkit/snippets/slider.php#L16

Category thumbnail: https://github.com/samnabi/shopkit/blob/7b07e2b9c99c3962dbe3855b84c9e4cc666890f6/site/plugins/shopkit/snippets/list.category.php#L9

Product thumbnail: https://github.com/samnabi/shopkit/blob/4a2c556e91b90531d30a09ec1ebc959b192f7452/site/plugins/shopkit/snippets/list.product.php#L9

Resize upon file upload in the panel: https://github.com/samnabi/shopkit/blob/518fb6b6eeb0c4e819db9a2134c1c182c72822ed/site/plugins/shopkit/registry/hooks.php#L25

**Comment by Mojo90** [comment]
Thank you!
