### ISSUE TITLE
PDF Download

### ISSUE THREAD

**Issue by Mojo90** [samnabi/shopkit#207]
I wanted to provide only a download when a product variant is purchased. But it only downloads a wrong .html file with the following errors, when I press the download Link:

<img width="1244" alt="screen shot 2018-06-09 at 15 18 06" src="https://user-images.githubusercontent.com/2122156/41192094-61245d82-6bf9-11e8-9947-758fa81608aa.png">
<img width="1920" alt="screen shot 2018-06-09 at 15 18 12" src="https://user-images.githubusercontent.com/2122156/41192095-6142b23c-6bf9-11e8-8428-5a7a6efa886d.png">

**Comment by samnabi** [comment]
Have you applied the changes from this commit? https://github.com/samnabi/shopkit/commit/99b430ec961a1854fb1c9e23f47e79fccdc66222

**Comment by Mojo90** [comment]
Perfect 👌🏿, sorry did not see that
