### ISSUE TITLE
Buy Shopkit License

### ISSUE THREAD

**Issue by Mojo90** [samnabi/shopkit#208]
I am unable to buy a license. When I am in my cart I there is no button like `Pay` or so? (pls see the attached pdf of my cart)

[Cart · Shopkit.pdf](https://github.com/samnabi/shopkit/files/2091670/Cart.Shopkit.pdf)

**Comment by samnabi** [comment]
This was a bug – now fixed (both on my site and in the Master branch!)

https://github.com/samnabi/shopkit/commit/2a8baded202ab318fd30e7ce5993c128115093b3
