### ISSUE TITLE
Category wrong presentation in IE

### ISSUE THREAD

**Issue by Mojo90** [samnabi/shopkit#209]
In internet explorer the category overview does not look very good, one can not read the category name as the picture attached shows: 
![2018_06_19_12_37_48_shop_federleicht_designatelier_internet_explorer](https://user-images.githubusercontent.com/2122156/41596288-26d7af16-73ca-11e8-9934-67aafa2066dd.png)

In the normal other browsers (Safari, Chrome, Firefox) it is shown correctly: https://federleichtdesignatelier.de/shop

**Comment by samnabi** [comment]
The shadows should now show up properly on IE11: https://github.com/samnabi/shopkit/commit/fba71f5efd727f3326da2fd88537e59603e2ccd1
