### ISSUE TITLE
Register/Login fails, permissions?

### ISSUE THREAD

**Issue by plagasul** [samnabi/shopkit#211]
I've just uploaded shopkit, as downloaded from its website, to a hosting.

I visit the site and attempt to register, then I am directed to login fail page.

No file seems to be created under /site/accounts/

Alternatively I tried to create an account locally (it works) and then upload it to the remote site/accounts folder but I still get login fail when attempting to login.

Permissions of site/accounts folder seems to be 755, I do not have shell access, only ftp.

Site/accounts permissions seem to be 755, changing it to 775 does not do anything either.

**Comment by samnabi** [comment]
@plagasul can you verify that the same apache user owns the script and is executing it?

What is the output of the following two PHP commands? They should be the same.

`get_current_user();`

`exec('whoami');`

**Comment by plagasul** [comment]
I created a test.php file with those commands. It returns an error," exec has been disabled for security reasons". Removing the exec, and adding an echo to get_current_user() I get the name of an user, but I can't compare it with 'whoami', because I can't run it.

The username I get is not www-data or similar. It is the same username from Cpanel.

I have a regular, working kirby installation on the same webspace, just up a folder, and using the same file and command I get the same user.

**Comment by plagasul** [comment]
This has been solved. To be honest I do not understand how, but it is solved. Perhaps this was a mistake on my side. I'll get a license now, thanks.

**Comment by samnabi** [comment]
Thank you for keeping the issue updated here. Some of the most confusing issues happen with server setups. Glad it's working for you know.
