### ISSUE TITLE
The page UID exists

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#214]
Hi Sam!
From time to time I get the following error when I add a product to the cart. It’s related with the creation of the order? Any way to fix this quickly is kind of urgent :)

![captura de pantalla 2018-10-03 a las 11 53 43 a m](https://user-images.githubusercontent.com/1755590/46419260-dceaba00-c703-11e8-858c-602e21285a75.png)

thanks in advance. Best!

**Comment by samnabi** [comment]
Hmm. When a transaction is created, it uses the Session ID as the URI for the transaction page.

Here's the relevant code, within the `add()` function in `site/plugins/shopkit/shopkit.php`.

```
// Create the transaction file if we don't have one yet
  if (!s::get('txn') or page(s::get('txn'))->intendedTemplate() != 'order') {
    $txn_id = s::id();
    $timestamp = time();
    page('shop')->create('shop/orders/'.$txn_id, 'order', [
```

So somehow there is an existing Session, which has already created an order, and then later on in that same session the file tries to get created again.

Can you specify the steps to replicate this, is there a series of actions before you add the product to the cart? (i.e. are you logged in or not, which actions do you do before hand)

**Comment by guidoferreyra** [comment]
I deleted some orders and I couldn‘t replcate the error. It happens from to time to time. Im going to investigate after I manage to solve a major issue I have. Im just opening another issue sorry, asking for your help. Don‘t hate me please :)

**Comment by samnabi** [comment]
I believe I've found the fix for this. I wasn't handling the error states properly when checking for an existing transaction file. Should be fixed now with the latest commits on Master: https://github.com/samnabi/shopkit/commit/db9ab0792088188b8c4ee2e5a46d0b02793c66bd
