### ISSUE TITLE
Shipping cost not calculated in Paypal

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#215]
When I place an order the cart has the correct shipping cost, the order details also... but when I go the last step in Paypal the total doesn’t include the shipping costs.

Can you please point me where to look to solve this. I’m trying to know If I messed up some shopkit code.

Thanks in advance

**Comment by samnabi** [comment]
What does your `process.php` file look like for the PayPal gateway? This is the relevant code: https://github.com/samnabi/shopkit/blob/master/site/plugins/shopkit/gateways/paypalexpress/process.php#L28

The shipping value should be stored in a hidden form field that gets sent to the PayPal screen. According to [PayPal's documentation](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#individual-items-variables), the form field should be called `shipping`.

But Shopkit's is called `shipping_1` – I wonder if PayPal has changed their API?

Can you edit the `process.php` file and see if it works with the following code in line 28?

```
	<input type="hidden" name="shipping" value="<?= $txn->shipping() ?>">
```

**Comment by guidoferreyra** [comment]
Yes, that’s the file I was looking but I didn’t make any modification on I use the one from shopkit.
I tried changing the line 28 as you said me but the error persists.

Maybe paypal changed the API? Could you reproduce the error? 
FYI im using the specific product shipping rates. Maybe is related with that?

Thanks!

**Comment by guidoferreyra** [comment]
I think I solved changing in the paypal `process.php` file the line 28 to this

```<input type="hidden" name="shipping_1" value="<?= (float)$txn->shipping()->value + (float) $txn->shipping_additional()->value ?>">```

**Comment by samnabi** [comment]
You're right, the additional shipping rules were not being factored in during the PayPal shipping calculation. (They were already in place for the other gateways). Thanks for finding that one!

Fixed in https://github.com/samnabi/shopkit/commit/e26416713d5ab80d652571434862e52daadecc0e
