### ISSUE TITLE
Paypal status on pending in sandbox

### ISSUE THREAD

**Issue by thomasverleye** [samnabi/shopkit#216]
reference: #176 

Hi, Is it possible to test the paypal sandbox payment on a local test environment with a self-signed certificate? I've been testing this but I can't seem to figure how to get this working locally, the payment status keeps on stating `pending`.

**Comment by thomasverleye** [comment]
I've been testing paypal payment on the live environment now and I've encountered this same problem. The payment status stays on `pending`, when trying to use paypal in sandbox mode.

**Comment by thomasverleye** [comment]
the reason why this was still on pending was because the PHP mailer didn't work, I've fixed it by using Mailgun instead.

**Comment by samnabi** [comment]
Re-opened this ticket, I think it's a big enough issue to address with a bugfix. Better error handling in the gateway callback could be helpful here.

**Comment by thomasverleye** [comment]
That, and the feature you mentioned in #169 would also be helpful. Lot's of servers aren't enabling PHP mailer so something like selecting another mail service is a must here. I've had to modify your plugin source code in order to make things work.

**Comment by samnabi** [comment]
Have you had to update any code other than the [sendMail() function](https://github.com/samnabi/shopkit/blob/master/site/plugins/shopkit/shopkit.php#L657) in `shopkit.php`?

**Comment by thomasverleye** [comment]
Hi @samnabi ,

No, nothing other than the sendMail() function indeed. I've also added some log functions in the PayPal Callback to look whereabouts the script got stuck.
