### ISSUE TITLE
Residual shipping cost when removing item from the cart

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#217]
Hi Sam.
I noticed when I add to the cart a product that has a custom shipping rule and after I remove it the shipping cost doesn’t dissapear.

Any help? Best.

**Comment by guidoferreyra** [comment]
Hi Sam sorry for bother you again with this but it’s very important to me solve it soon.
Best!

**Comment by samnabi** [comment]
@guidoferreyra This is now fixed in the latest commit: https://github.com/samnabi/shopkit/commit/6da007874e6ae0b29145c7b0e4fd71f2a75471ad
