### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#218]
Hi Sam!
I noticed that the order files that are modified by Paypal info like adding, for instance, `payer_name` are changed from utf8 to Wester (Windows 1252) and this change accented names on orders page 
![captura de pantalla 2018-10-26 a las 6 38 22 p m](https://user-images.githubusercontent.com/1755590/47593638-629e0600-d94e-11e8-8fb6-297b9538a08f.png)

And also sometimes breaks the generation of pdf invoices leading to debug page.

any ideas?

**Comment by samnabi** [comment]
I believe this is an issue with PayPal's encoding settings.

PayPal uses windows-1252 encoding by default, which doesn't support accented letters. You may also need to change your PayPal account settings to use UTF-8: https://formsmarts.com/enable-utf-8-encoding-paypal
