### ISSUE TITLE
2 Factor Auth Payment Regulation EU

### ISSUE THREAD

**Issue by Mojo90** [samnabi/shopkit#221]
Hi,
you heard of this new regulation which comes into effect in September 19 in the EU?
https://internetretailing.net/themes/themes/new-eu-regulation-will-require-a-two-factor-payment-authentication-to-protect-retailers-mastercard-18031
What I read is that at least Stripe will change their API. Do you know if there need to be some changes with your payment integration or if it will still work as usual?
Btw: I am still very happy with your shopkit and until now I discovered no more problems so far :)!

**Comment by Mojo90** [comment]
Hi,
do you have any update on this? I just got an e-mail from Stripe:

```
Action required to prepare for upcoming SCA regulation
[...]
Starting 14 September, Strong Customer Authentication (SCA) regulation will require two-factor authentication on many payments in Europe. Payments without SCA may be declined. You’ll need to update your integration by 14 September in order to avoid an increase in declined charges.
[...]
```

And I would not encounter any payment errors from Mid of September on.

**Comment by samnabi** [comment]
Shopkit v2.7 updates the Stripe Checkout gateway to use SCA.
