### ISSUE TITLE
Order Notification not working

### ISSUE THREAD

**Issue by marcteys** [samnabi/shopkit#225]
I'll make it simple. I couldn't receive a notification email after each purchase. 
Here is the fix: 

> line 34 of `snippets\order.callback.php`  replace` if (strpos($item->uri(), trim($uid)))` by ` if (strpos($item->uri(), trim($uid))!== false)`

Some PHP version don't  return a boolean to  strpos( , ).

**Comment by samnabi** [comment]
Thank you!
