### ISSUE TITLE
Issue with login in a subdirectory installation

### ISSUE THREAD

**Issue by designtemple** [samnabi/shopkit#39]
Everything seems to be working fine except the login function as it redirects to mydomain.com/login instead of mydomain.com/shopkit/login.

Using the latest v1.0.2 Shopkit with Kirby 2.2.3.

**Comment by designtemple** [comment]
This has been solved. Had to use a subdomain. http://shop.mydomain.com works fine.

**Comment by samnabi** [comment]
This is a bug, it will be fixed in the next release. To fix this redirect issue now, you can edit `/config.php` by replacing the first route with this:

```
  array(
    'pattern' => 'login',
    'method' => 'POST',
    'action'  => function() {
      if($user = site()->users()->findBy('email',get('email')) and $user->login(get('password'))) {
        return go(site()->url());
      } else {
        return go(site()->url().'?login=failed');
      }
    }
  ),
```
