### ISSUE TITLE
Currency change affects all orders retroactively

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#4]
When the currency is changed in the `/shop` settings, all listings on the `/shop/orders/` page get retroactively switched.

I don't want to embed currency symbols in the price/shipping/tax amount fields, but perhaps each order needs its own defined currency field.

**Comment by distantnative** [comment]
I know this is a stretch, but maybe introducing a feature to define prices per currency per product. Which would be a pre-step to multi-currency stores.

But simply letting me say that a product is 9.99 in USD but 8.99 in EUR. Then each order would point directly to a price which is tied to a currency, no matter if the global shop currency is changed.

**Comment by samnabi** [comment]
Paypal's API requires you to define one currency code for each transaction, so I don't think it's possible to have products with different currencies on the same order.

Multi-currency stores are a great idea -- I see them working very similarly to Kirby's multilanguage setup. There would need to be some fallback exchange rates for products that only have one currency defined.

**Comment by distantnative** [comment]
Oh yea, sorry if I was unclear, but one order clearly should just have one currency.
