### ISSUE TITLE
Digital products

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#45]

**Comment by samnabi** [comment]
Temporary link request:

> For selling the fonts, I'll need to be able to deliver digital goods to users -- and I'm wondering if you had any suggestions on how to modify your Shopkit to do that? I'd need to be able to deliver a temporary download link upon payment. Any tips would be extremely appreciated!

**Comment by samnabi** [comment]
Sneak peek.

![screen shot 2016-07-27 at 10 12 46](https://cloud.githubusercontent.com/assets/1731536/17178248/b03cee74-53e2-11e6-903a-7f0552ee4560.png)

**Comment by invasoria** [comment]
Looking great! Is that inside a price variant?

**Comment by samnabi** [comment]
Yes, that way you can offer different downloads for different price variants. It seems like the most logical place to put them.

**Comment by samnabi** [comment]
Download links show up in the `View orders` page, which the customer already gets directed to after a purchase.
![screen shot 2016-07-27 at 15 03 39](https://cloud.githubusercontent.com/assets/1731536/17188515/6165e76e-540b-11e6-89de-791171c1538b.png)
![screen shot 2016-07-27 at 15 02 59](https://cloud.githubusercontent.com/assets/1731536/17188520/6362b880-540b-11e6-8613-7fdb4131d4ab.png)
