### ISSUE TITLE
Shipping cost by weight and by price fails.

### ISSUE THREAD

**Issue by designtemple** [samnabi/shopkit#52]
When adding an item to the cart, the shipping method is applied correctly to the country, but the shipping rate for each item fails to apply. This does not apply for flat rate shipping, only for shipping by weight and by price.

I have created 2 shipping methods, one for European countries and one for the rest of the world. Whatever country is selected the correct shipping method is returned, but the shipping cost for items in the cart is returned null.

Example of the Shipping variable in the content/shop.txt file:

```
Shipping: 

- 
  method: Air Mail Priority A – Zone 1
  countries: >
    andorra, austria, belgium, bulgaria,
    croatia, czech-republic, denmark,
    estonia, finland, france, germany,
    greece, hungary, iceland, ireland,
    italy, latvia, liechtenstein, lithuania,
    luxembourg, malta, monaco, netherlands,
    norway, poland, portugal, romania,
    san-marino, slovakia, slovenia, spain,
    sweden, switzerland, united-kingdom
  flat: “”
  item: “”
  weight: |
    20 : 2.50
    50 : 4.50
    1000 : 17.50
    2000 : 21.00
    3000 : 24.00
    4000 : 27.00
    5000 : 30.00
  price: “”
  calculation: low
- 

```

**Comment by designtemple** [comment]
Figured out how to fix the issue. The issue is with the check to see if shipping is charged for an item or not. `Cart.php`, line 172. Currently, the if statement checks to see if `$item->noshipping` is empty, I changed this to check whether it is true and it worked:

```
 // If shipping applies, add this item to the calculation for applicable amount and weight 
                if ($item->noshipping) {
                    $this->shippingAmount += floatval($item->amount) * $quantity;
                    $this->shippingWeight += floatval($item->weight) * $quantity;
                }
```

**Comment by samnabi** [comment]
Thanks for reporting. I'm confused about your code fix though, you've changed it to calculate shipping for products that specify `noshipping`.

**Comment by designtemple** [comment]
Hey there,

No problem, great work on the Shopkit plugin, it’s a really great piece of work.
Yes it is a bit confusing, but i tried check to see if noshipping is not specified and it doesn’t work.

Thanks,
Alex

**Comment by samnabi** [comment]
This has been resolved on the `dev` branch. See this commit for more details: https://github.com/samnabi/shopkit/commit/d928341bb955adb2541322301aeea12e5e894e6f
