### ISSUE TITLE
Set tax rate per product

### ISSUE THREAD

**Issue by samuellinde** [samnabi/shopkit#63]
In Sweden, taxes (value added, VAT) are based on the type of product sold. Most goods and services have a 25% VAT (included in the displayed price), but books have a 6% VAT.

The ability to set the tax rate on the product instead of a as a general setting would be helpful.

**Comment by samnabi** [comment]
Jogged my memory: https://github.com/tobiastom/tax-database

**Comment by samnabi** [comment]
More resources: http://opendata.stackexchange.com/questions/878/what-sources-exist-for-sales-tax-information

**Comment by samuellinde** [comment]
Or just leave it up to the admin to enter tax rates. I think the system shouldn't be responsible for knowing all possible possible tax rates (plus keeping up with changes would be a headache). But assigning different tax rates to different products would go a long way.

**Comment by samnabi** [comment]
It's a good suggestion. We have similar rules here in Canada, children's clothes etc. are taxed less. I was hoping there was a large coordinated open-source effort to keep these rates up-to-date, but I guess that was optimistic of me :)

Other e-commerce software like WooCommerce leaves it up to the admin. I'll keep this open for discussion, probably won't get to this feature until the summer though.

**Comment by samnabi** [comment]
In Shopkit 1.1, products will have a new **Custom tax rates** field instead of the previous `notax` checkbox.

![screen shot 2016-07-14 at 10 50 53](https://cloud.githubusercontent.com/assets/1731536/16843847/def0da6e-49b0-11e6-947e-b9d65b28838d.png)
