### ISSUE TITLE
Total doesn't seem to update on item quantity change

### ISSUE THREAD

**Issue by ToGe88** [samnabi/shopkit#66]
Hey there,
it seems that, if i change the quantity of an item, that the total amount is not changing. I attached two screens to show you what's going on. Maybe it's because i did some changes because of the tax include/exclude problem, but if i use your default cart-file it's still the same. What could be the problem? Maybe something with caching? Because the page is still refreshed, so it shouldn't remember the old amount, doesn't it?

Thanks for your help.
Tobi

![bildschirmfoto 2016-05-08 um 12 49 54](https://cloud.githubusercontent.com/assets/8841530/15097462/12927586-151c-11e6-88e8-67ee462e7b15.png)
![bildschirmfoto 2016-05-08 um 12 49 41](https://cloud.githubusercontent.com/assets/8841530/15097463/180cd920-151c-11e6-8b05-4f5c7d31631b.png)

**Comment by samnabi** [comment]
Good catch. Shopkit was keeping an old version of the shipping rates in session storage.

I'll add some code to refresh the shipping numbers whenever the cart quantity changes, or when the country changes (these are the two things that affect shipping).
