### ISSUE TITLE
Different shipping costs in checkout vs. orders summary

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#69]
Seems to occur with shipping calculated by weight.

![bildschirmfoto 2016-06-10 um 18 50 00](https://cloud.githubusercontent.com/assets/1731536/16081499/a4b4c810-32db-11e6-94c8-568e107eb28e.png)

![bildschirmfoto 2016-06-10 um 18 50 12](https://cloud.githubusercontent.com/assets/1731536/16081506/aeeeaac6-32db-11e6-8e5f-5bdbc95efbf0.png)

**Comment by samnabi** [comment]
It looks like this bug has the same root cause as Issue #66.

This will be fixed in 1.0.5. When it's released, check commit 9aa738b959d5f54939b519a20ac378af237e3a5c to see the exact changes that fixed this bug.

**Comment by lareus** [comment]
So can i see somewhere which file was fixed for this issue?

I modified some files, so i dont want do upload all files and replace them, otherweise i would lose many individual changes...
