### ISSUE TITLE
Postage not recalculating

### ISSUE THREAD

**Issue by swightwick** [samnabi/shopkit#75]
I have the latest version running at stage.lesseffort.co.uk

When you buy an item (use the MPC t-shirt) Postage rates do not get applied properly. It seems to take whatever the default countries rate is. If you change to a european country the relevant post cost shows up and there is a refresh, but the grand total is not recalculated.

**Comment by samnabi** [comment]
Hi Sam, I suspect this issue has the same root cause as #66 and #69. I have found a fix for the buggy code and will be issuing a new release (version 1.0.5) in the next day or two which will fix this.
