### ISSUE TITLE
Bug after cancelling order from PayPal

### ISSUE THREAD

**Issue by invasoria** [samnabi/shopkit#77]
Steps to reproduce this issue:
- Use PayPal as payment method (Shopkit will create the pending order file).
- Cancel PayPal order and return to store.
- If you try to pay again with PayPal, no matter what, Shopkit will create another pending order and just refresh the cart page, nothing else.
- Press "Pay Now" again and it will now work. It will create yet another pending order file.

Issue has been happening since 1.0.4

**Comment by samnabi** [comment]
This will be addressed in 1.1, where I'm planning a better approach to session variables.
