### ISSUE TITLE
Include a quantity selector to add multiple items to cart

### ISSUE THREAD

**Issue by invasoria** [samnabi/shopkit#80]
I think this would be cool. Sometimes it makes sense to add more than one item from the product page.

**Comment by samnabi** [comment]
Makes sense. If I introduce this feature it might also be worthwhile to specify the default quantity and permitted increments in a blueprint.

(i.e. selling tea in bulk starts at 100 grams and you can increase the quantity in 50-gram increments)

**Comment by samnabi** [comment]
https://forum.getkirby.com/t/shopkit-commerce-plugin/1476/139?u=samnabi

**Comment by invasoria** [comment]
I've done this a couple of times before and as far as I remember, I didn't have to modify a lot of things, just the product template (please correct me if I'm wrong). The Cart.php, CartItem.php and cart.php controller, they all already have a $quantity defined.

A quick example from a shop that sells tickets:

http://codepad.org/hX8HHd55

Edit: Can't seem to paste the correct code here so I used a private CodePad post.

**Comment by samnabi** [comment]
The more I think about this, the more I dislike it.

I think the Cart page is the most logical place for customers to handle quantity, and I want them to make a few decisions as possible before arriving on the Cart page.

I also don't want to introduce too much complexity to the Product page blueprint. It already has a lot going on.

The new theme in v2.0 uses AJAX quantity selectors, so changing quantity will be much faster and smoother than before.

I'm inclined to close this unless you'd like to discuss further.

**Comment by invasoria** [comment]
Yes, I see what you mean.

A quantity selector works better on a "Quick Checkout" type of store where no order or cart reviewing is available, and that is not the case here. Anyway, the great thing about Shopkit is that its logic is flexible as hell, so that can be done with a little tweaking and testing.

 You should totally close this if it doesn't suit your product vision.

**Comment by samnabi** [comment]
Okay, I will close it then :) I hope you like the new AJAX quantity selectors coming in 2.0!
