### ISSUE TITLE
Keep user on same page after adding product to cart

### ISSUE THREAD

**Issue by invasoria** [samnabi/shopkit#81]
When a user adds a product to cart they are taken straight to the cart page. Sometimes this is very annoying for some users that like to keep shopping/browsing for more stuff. I'd like to suggest a couple of options for the panel to let the store admin choose the behavior of the add to cart process: 

a) Use a "Buy" button to send the user to the cart page, for a quick shopping experience.
b)  Use an "Add to Cart" button to refresh the page to let the user stay at the same page and show an "added to cart" message.

**Comment by samnabi** [comment]
This behaviour was a conscious choice to try to reduce cart abandonment.

In my mind, the product page isn't much use to a customer after they add an item to the cart. I don't think it's any more annoying to search for your next product starting from the cart page?

**Comment by samnabi** [comment]
https://forum.getkirby.com/t/shopkit-commerce-plugin/1476/87?u=samnabi

> Without getting into the UX discussion: You could make it an option to redirect back to the product after it has been added in the cart controller. Then there's no need to add the code to the product controller.

**Comment by invasoria** [comment]
Great! Never thought of doing that before, I believe it's quite a functional (even elegant) solution.

And by "very annoying for some users" I was referring to a client who has strong feelings against the redirection to the cart. Didn't mean to sound like a horrible person, apologies if I did.
