### ISSUE TITLE
Paypal: Error Detected

### ISSUE THREAD

**Issue by isospin** [samnabi/shopkit#82]
When i try to checkout (on demo page and on the freshly downloaded version from github) i got this error: 

`The link you have used to enter the PayPal system contains an incorrectly formatted item amount.`

![unbenannt](https://cloud.githubusercontent.com/assets/1148347/17085817/197b0ebe-51e2-11e6-97eb-ee45a0256add.PNG)

**Comment by samnabi** [comment]
Please see the latest commit: https://github.com/samnabi/shopkit/commit/a68aef88b141af2902a41b9d7919096e337b6443

Does this happen if you download the [latest code from the master branch](https://github.com/samnabi/shopkit/archive/master.zip)? This will be more up-to-date than the releases page.

**Comment by isospin** [comment]
no. it was shopkit-v1.0.5.zip

**Comment by samnabi** [comment]
Great. This will be fixed in the next release, then. For an immediate hotfix, you can edit `site/snippets/cart.process.paypal.php` as shown in commit https://github.com/samnabi/shopkit/commit/a68aef88b141af2902a41b9d7919096e337b6443
