### ISSUE TITLE
Is there any fraud-prevention?

### ISSUE THREAD

**Issue by anselmh** [samnabi/shopkit#83]
Hey there,

does shopkit have any fraud prevention built-in or supports that? For example, checking if address matches credit card country, queuing charges and similar techniques that, for example, Stripe [advises](https://helloanselm.com/notes/stripe/#a-call-with-a-stripe-person)[1] [to](https://support.stripe.com/questions/avoiding-fraud-and-disputes)[2] [implement](https://stripe.com/docs/guides/fraud/benchmarks)[3]?

Thanks for any insight, statement, roadmap indication :)
—Anselm

**Comment by samnabi** [comment]
There is some basic validation in the [PayPal callback code](https://github.com/samnabi/shopkit/blob/master/site/snippets/payment.success.paypal.php#L9) to make sure that the transaction amount and currency matches what was in the Customer's shopping cart. If there's something wrong, it will alert the site owner with an email.

Fraud prevention is going to be a little different for each payment gateway, each one needs to implement their own checks before marking a transaction as "paid" in Shopkit.

I agree that more work can be done in this area. In Shopkit 1.1, all this gateway validation will happen in a standardized file, `site/plugins/shopkit/gateways/gateway-name/callback.php`. So it will be easier to pinpoint what kind of fraud prevention each gateway is doing.

**Comment by anselmh** [comment]
Okay, thanks a lot!
