### ISSUE TITLE
VATMOSS support?

### ISSUE THREAD

**Issue by anselmh** [samnabi/shopkit#84]
Does Shopkit provide support for VATMOSS (buyer-based applied VAT rates): http://ec.europa.eu/taxation_customs/resources/documents/taxation/vat/how_vat_works/telecom/one-stop-shop-guidelines_en.pdf?

**Comment by samnabi** [comment]
How does this program work? Right now, tax rates are set based on the customer's self-declared country in the Cart page.

Does VATMOSS let customers pay a different rate than would be typically applied to people in their country? How does a website validate their claim?

**Comment by anselmh** [comment]
So, in fact, it seems it already follows kind of the VATMOSS principle. VATMOSS means that electronic purchases (such as ebooks, downloads, etc) need the VAT tax of the buyer’s country applied. This needs to be verified by two factors (could mean 1st check by address, 2nd by matching credit card country to address, or geolocation), according to the technical guidelines by the EU. There are two issues in the implementation usually:
1. Getting two country confirmations is hard, UX-wise (geolocation detection would prevent travelling people to purchase something, credit card only works if you offer credit card payment and get the country data).
2. Have an up-to-date list of VAT rates of the whole EU.

However, I wonder if that’s the correct way to do for real products. I think in the EU normally you charge the VAT of the merchant’s country for real, non-digital products.

Hope this helps a bit. Here are more resources about it https://rachelandrew.co.uk/archives/tag/vat.

**Comment by samnabi** [comment]
I'm learning that tax rates are one of the most complicated things about e-commerce 😦

I'm in Canada, where each province has a different tax rate. If I sell to customers within Canada, I charge 13% HST. But if they're from another country, it's considered an "export good" and I charge 0% HST.

It's all very confusing!

**Comment by anselmh** [comment]
Yeah, in the EU it’s even more complex since we make a difference between inner-EU, outer-EU, in-country purchases and finally there are differences if you sell a service, physical or digital product and if you sell to someone who has a VAT ID or not.

**Comment by samnabi** [comment]
I'll mark this closed for now. If there are any features missing from Shopkit that would be helpful for managing tax rules, please comment below!
