### ISSUE TITLE
Call to undefined function mime_content_type()

### ISSUE THREAD

**Issue by guidoferreyra** [samnabi/shopkit#87]
Hi Sam.
I’ve installed the last version of shop kit and I’m getting the following error when I’m testing the shop in the ftp. "Call to undefined function mime_content_type() in [...]site/plugins/shopkit/templates/cart.php".
Is this related to the php version of my host or what? I’m running on 5.6.

Best regards!

**Comment by samnabi** [comment]
Hm, I use this function to display the Payment Gateway logos.

After a bit of googling, it looks like [some PHP builds don't include `mime_content_type()`](http://php.net/manual/en/function.mime-content-type.php). That's a shame.

As a quick fix, you could replace line 250 in `/plugins/shopkit/templates/cart.php` with this:

``` php
$logo_src = 'data: png;base64,'.$logo_data;
```

**Comment by samnabi** [comment]
Well it turns out Kirby already has a method for this: https://getkirby.com/docs/toolkit/api/f/uri
