### ISSUE TITLE
Order confirmation and update language

### ISSUE THREAD

**Issue by invasoria** [samnabi/shopkit#88]
The current configuration of the "**confirm.php**" controller only updates the order for the english language. Since I'm developing a spanish-language-only store I had the issue of orders not updating correctly. I solved this by simply creating and overriding the controller with a new one by editing the language variable in the update function but I guess it would be cool to have a multiple language functionality out-of-the-box in the future.

**Comment by samnabi** [comment]
I see, so you have changed your default language in `/site/config/config.php` to Spanish?

**Comment by invasoria** [comment]
Yes, I changed it to Spanish and removed other language options.

**Comment by samnabi** [comment]
Okay, I could update the `confirm.php` controller to use [`$site->defaultLanguage()`](https://getkirby.com/docs/cheatsheet/site/default-language) instead of hardcoding `en`.

Seems like a simple fix.

**Comment by invasoria** [comment]
Yes, that would work!  :smiley: 

Oh, just a quick thought: In the case of a multilingual site, you'd need to update the orders for all languages, right?

**Comment by samnabi** [comment]
For the most part, the `order.en.txt` file shouldn't need to be translated. Its content is never viewed or edited directly (individual orders are hidden from the panel).

The only things that may need to be translated are the product name, variant and option... they are currently hardcoded in `order.en.txt` in the default language. This information needs to be hardcoded in case the product details change in the future. But should it be in the default language or the customer's language... ?

I will think about this.
