### ISSUE TITLE
Prevent file download snooping

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#89]
From https://forum.getkirby.com/t/introducing-shopkit/1476/95

> By the way, a much more bigger problem is that the link to the downloadable product via the "Order" page have an url that allows to deduce the possible location of other products and illegally download them

**Comment by samnabi** [comment]
Does it make sense to pipe these file downloads through a route to avoid URL snooping?

**Comment by samnabi** [comment]
It's not like someone can access an indexOf file list, so... I'm not convinced this is a big issue. They would have to guess the filename anyway.

Shopkit could show the file urls as hashed filenames in a `/download` route, which makes them harder to guess but results in more work on the server side to loop through files and compare hashes.

**Comment by samnabi** [comment]
As there hasn't been any followup discussion to justify cloaking the download URLs, I'll close this issue for now.

**Comment by guidoferreyra** [comment]
Sam, sorry for the delay I was on a trip. For me is a very important issue because in my product/folder structure is very easy to guess the url for other products. What do you recommend me?
Thanks in advance.

**Comment by samnabi** [comment]
I just don't understand how is it easy to guess the URLs for other products. Can you give me an example?

**Comment by guidoferreyra** [comment]
Yes. Im setting up a cart for selling fonts, So if you buy one weight you know the url and you can guess other weight URLs. For instance /nameoffont-light.otf and /nameoffont-bold.otf

**Comment by invasoria** [comment]
How about making a zip file for every font with a randomly generated filename? That way guessing the zip filename would be close to impossible.

**Comment by invasoria** [comment]
Oh, and that way, also, you could include a text file or a use-sample PDF with the download, like most foundries do with their downloads.

**Comment by guidoferreyra** [comment]
Yes It's an option but is not the most confortably option because first you
have to generate all the zips with the random name and is not easy to know
what are you doing while you are in the panel.

**Comment by samnabi** [comment]
Would it not be enough to have a random suffix on the zip file to prevent guessing? Like `font-family-name-bold-61143193651.zip`

**Comment by guidoferreyra** [comment]
Good idea Sam, thanks! 
Although I think having visible and static links go against the expire download feature.
Regards.

**Comment by samnabi** [comment]
My main concern is that obfuscating the download links will put a lot of pressure on the server and add lots of complexity.

But you raise some good points, perhaps there should be a route that finds the appropriate file and makes sure it's not expired before serving a file.
