### ISSUE TITLE
Notification emails not working

### ISSUE THREAD

**Issue by invasoria** [samnabi/shopkit#93]
I've tested a plain Shopkit installation on two different servers (PHP 5.6 and PHP 7) and notification messages are not working. It's kinda strange since the previous version of Shopkit did send notifications with no problems.

Is anyone else experiencing this?

**Comment by DodoVoelkel** [comment]
I kind of have the same problem. Additionally my Stock wont update after a successful order. Seems to have something to do with the callback script.
Have you tried registering a new user via the frontend? The activation email is sent correctly on my installation, so the problem isnt the mailscript itself.

**Comment by invasoria** [comment]
Funny. Just like you pointed out, stock isn't working either. I haven't tried the user functions via frontend, the project I'm working on needs only unregistered sales but I'll test that too.

For the emails, I ended up integrating PHPMailer at the callback today. Just a quick and dirty PHPMailer function to notify the user with an HTML template through SMTP after a purchase is made.

I'll be looking at the callback files to see if I can identify what's going on.

**Comment by samnabi** [comment]
Thanks for identifying these issues, I'll look into it.

**Comment by samnabi** [comment]
Are these issues happening with all gateways?

**Comment by DodoVoelkel** [comment]
For me it happens with PayPal and Paylater. Hadnt tried stripe.

**Comment by samnabi** [comment]
The notification emails were failing silently because the snippet didn't know what language to use. I've fixed that in the dev branch.
