### ISSUE TITLE
Tabs vs headings in Panel

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#95]

**Comment by samnabi** [comment]
If anyone has strong opinions about using [tabs](https://github.com/afbora/Kirby-Tabs-Field) vs. [headlines](https://getkirby.com/docs/cheatsheet/panel-fields/headline), please comment here.

**Comment by samnabi** [comment]
The tabs plugin can cause display wonkiness on some devices. I'm inclined to use headings, as they are built in to Kirby and will make the Panel behaviour more standardized and future-proof.

**Comment by samnabi** [comment]
[Continuing this debate with myself] On the other hand, Headlines make the Product/Shop pages very cluttered. Tabs, especially with their icons, can be easier to navigate and they are a good way to hide secondary settings (e.g. discounts)

**Comment by samnabi** [comment]
[Panel Group plugin](https://github.com/louiswalch/kirby-panel-group) combines accordion headlines with a visual grouping.

**Comment by seehat** [comment]
I also like the tabs interface, because it is easier to navigate and less cluttered.

**Comment by samnabi** [comment]
Okay, tabs it is! I will put in a pull request to the core tabs plugin to solve some of the display issues I've come across.
