### ISSUE TITLE
Stock doesn't update

### ISSUE THREAD

**Issue by samnabi** [samnabi/shopkit#98]
New issue split from discussion here: https://github.com/samnabi/shopkit/issues/93#issuecomment-248551656

@DodoVoelkel, can you inspect the text file itself to determine if stock is being updated? I know that if you stay logged in to the Panel while an order is happening, the Panel's own cache might override the stock value.

**Comment by DodoVoelkel** [comment]
Stock now updates with "Paylater" option.
Stock still doesn't update via Paypal. Also an order isnt set to "paid" after a successful transaction, even though i think i found a function somewhere in the code for it.
Maybe it has something to do with running via localhost? I will try it tomorrow on a server...
thanks for the support so far!

**Comment by samnabi** [comment]
PayPal can't access the `callback.php` file if it's on localhost, since PayPal can't access localhost :) 

I will run through some more tests to make sure this is working as expected.

**Comment by samnabi** [comment]
After some testing, I'm marking this as closed.

One common source of errors is having two `.txt` files in your product folder. If you end up with `product.en.txt` and `product.txt` in the same folder, this will cause issues with updating the content, including updating the stock.

Be sure to delete the `product.txt` folder, and ensure that there is only one content file per product. The language code should match your default language, set in `sites/config/config.php`
